
language: c++

git:
    depth: 1

addons:
    apt:
        packages: ['libboost-filesystem-dev', 'libboost-program-options-dev',
                   'zlib1g-dev', 'libbz2-dev',
                   'libexpat1-dev', 'libyaml-cpp-dev', 'libpq-dev',
                   'gettext-base', 'libpqxx-dev', 'pandoc', 'postgresql']

matrix:
    include:
      - os: linux
        dist: bionic
        compiler: gcc-7
        env: CC=gcc-7 CXX=g++-7
      - os: linux
        dist: bionic
        compiler: clang-7
        env: CC=clang-7 CXX=clang++-7
        addons:
            apt:
                packages: ['libboost-filesystem-dev', 'libboost-program-options-dev',
                           'zlib1g-dev', 'libbz2-dev',
                           'libexpat1-dev', 'libyaml-cpp-dev', 'libpq-dev',
                           'gettext-base', 'libpqxx-dev', 'pandoc', 'postgresql',
                           'clang-7']
      - os: linux
        dist: xenial
        compiler: gcc-5
        env: CC=gcc-5 CXX=g++-5

install:
  - git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git ../libosmium

before_script:
  - mkdir build && cd build
  - cmake -LA -DCMAKE_BUILD_TYPE=Debug -DOSMIUM_INCLUDE_DIR=../../libosmium/include ..
    # add stuff to install osm-logical here

script:
  - make VERBOSE=1 && ctest --output-on-failure

