name: Install PostgreSQL

runs:
  using: composite

  steps:
    - name: Install packages
      run: |
        apt-get update -qq
        apt-get install -yq --no-install-suggests --no-install-recommends \
            postgresql-${PG_VERSION} \
            postgresql-server-dev-${PG_VERSION} \
            postgresql-server-dev-all
      shell: bash
